---
name: cookiecontrol
---

PageController:
  extensions:
    - Hestec\CookieControl\CookieControlExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Hestec\CookieControl\CookieControlSiteConfig
